# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://git.speiyou.cn/huqichao1/test.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Test4Demo’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
end
